# Theme config.
[menu]
[[menu.main]]
  identifier = 'Home'
  title = 'Home'
  url = '/'
  weight = 10

[[menu.main]]
  identifier = 'Ideas'
  title = 'アイデア'
  url = '/ideas/'
  weight = 31

[[menu.main]]
  identifier = 'Fieldstones'
  title = '自然石'
  url = '/fieldstones/'
  weight = 32

[[menu.main]]
  identifier = 'TIL'
  title = 'TIL'
  url = '/til/'
  weight = 33

[[menu.main]]
  identifier = 'Tags'
  title = 'タグ'
  url = '/tags/'
  weight = 33

[params.home]
  maxItems = 9
  maxIdeas = 0
  maxStones = 0
  maxTIL = 0

[params.pagination]
  items = 6
  term = 4

[params.items]
  maxHoursToShowNew = 72
  maxHoursToShowUpdated = 240